# Generated by Django 4.1.7 on 2023-03-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.BigIntegerField(null=True),
        ),
    ]
