# Generated by Django 4.1.7 on 2023-03-03 22:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oneset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pcloudFolderId', models.CharField(max_length=250)),
                ('isUploaded', models.BooleanField(default=False)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('thumb', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('pincode', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(7)])),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('W', 'Working'), ('R', 'No Response'), ('D', 'Delivered'), ('C', 'Closed')], default='P', max_length=1)),
                ('venue', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=225)),
                ('quotation', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oneset.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oneset.location')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event_management.customer')),
                ('mutuals', models.ManyToManyField(related_name='mutualEvents', to='event_management.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('value', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event_management.event')),
                ('paymode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oneset.paymode')),
            ],
        ),
        migrations.CreateModel(
            name='EventWorkStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saveTheDate', models.CharField(choices=[('D', 'Done'), ('P', 'Pending'), ('N', 'None')], default='N', max_length=1)),
                ('promo', models.CharField(choices=[('D', 'Done'), ('P', 'Pending'), ('N', 'None')], default='N', max_length=1)),
                ('reels', models.CharField(choices=[('D', 'Done'), ('P', 'Pending'), ('N', 'None')], default='N', max_length=1)),
                ('trailer', models.CharField(choices=[('D', 'Done'), ('P', 'Pending'), ('N', 'None')], default='N', max_length=1)),
                ('song', models.CharField(choices=[('D', 'Done'), ('P', 'Pending'), ('N', 'None')], default='N', max_length=1)),
                ('fullVideo', models.CharField(choices=[('D', 'Done'), ('P', 'Pending'), ('N', 'None')], default='N', max_length=1)),
                ('rawData', models.CharField(choices=[('D', 'Done'), ('P', 'Pending'), ('N', 'None')], default='N', max_length=1)),
                ('photos', models.CharField(choices=[('L', 'Light Room'), ('D', 'Album Designing'), ('P', 'Album Printing'), ('N', 'None')], default='N', max_length=1)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='event_management.event')),
            ],
            options={
                'verbose_name': 'Event Work Status',
                'verbose_name_plural': 'Event Work Status',
            },
        ),
        migrations.CreateModel(
            name='AlbumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageId', models.CharField(max_length=300)),
                ('link', models.URLField(unique=True)),
                ('thumb', models.URLField(unique=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('pcloudFileId', models.CharField(max_length=250)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='event_management.album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event_management.event'),
        ),
    ]
